### ISSUE TITLE
RoadMap del proyecto

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1#34]
### Pendiente:
- [x] Crear el entorno
- [x] Preparar HTML y DOM
- [x] Preparar Llamadas AJAX
- [x] Testear la dinamica
