### ISSUE TITLE
Deberes pendientes (o no)

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1#75]
### Subir la solución y debatir + adelante :trollface: 
- [ ] Ejercicios de Libretas de contactos en [clase 36](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia36.md)
- [ ] Ejercicio de posicionar vehiculos de LA usando Google Maps en [clase 41](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia41.md#ejercicios)

### ¿Qué tenemos pendiente de solucionar?

- [ ] Ejercicio de formulario social con Firebase en [clase 43](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia43.md#ejercicios)
- [ ] Ejercicio de formulario social usando login social con Firebase en [clase 43](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia43.md#ejercicios)
- [ ] Ejercicio de desarrollar una aplicación para gestionar las peliculas que te gustan en [clase 45](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia45.md#ejercicios)
- [ ] Ejercicios de Regex en [clase 52](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia52.md#ejercicios)
- [ ] Crea las rutas básicas para tener una página web clásica en [clase 66](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia66.md#ejercicios)
- [ ] Crea las rutas básicas para tener una página web clásica con Express y Jade/Pug en [Clase 78](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia78.md#ejercicios)
- [ ] Versión APIrest + CORS + JADE del ejercicio de las peliculas en [Clase 78](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia78.md#ejercicios)
- [ ] Usuarios gestionen sus ficheros en Firebase en [clase 79](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia79.md#ejercicios)
- [ ] Migremos nuestra API de peliculas a un entorno serverless en [clase 79](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia79.md#ejercicios)
- [ ] Mejorar aplicación para ver streaming de Twitter en [clase 87](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia87.md#ejercicios)
- [ ] Chat con `Socket.io` en [clase 87](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia87.md#ejercicios) 

### Extras y revisiones

- [ ] [NASA Rover Challenge](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/49)
- [ ] [Refactorizar y mejorar nipstr](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/62)
- [ ] [Refactorizar QueQue.js a ES6+ en clase](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/58)

**Comment by UlisesGascon** [comment]
### Objetivos para el Viernes 06/04

- [ ] Crea las rutas básicas para tener una página web clásica con Express y Jade/Pug en [Clase 78](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia78.md#ejercicios)
- [ ] Ejercicio de desarrollar una aplicación para gestionar las peliculas que te gustan en [clase 45](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia45.md#ejercicios)
