### ISSUE TITLE
Scrapper Básico de Github Issues con puppeteer

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1#86]
-  En terminal `npm install puppeteer`
- `/scraper.js`
```javascript
// @see: https://www.youtube.com/watch?v=-Gtv6BMvcgM

const puppeteer = require('puppeteer'),
    fs = require('fs'),
    fileName = 'todo_peliculas'
let scrape = async () => {
    const url = 'https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues?q=is%3Aissue+is%3Aopen+label%3A%22Cultura+general%22';
    
    console.log("Arrancamos...");
    const browser = await puppeteer.launch();
    console.log("1. Puppeteer lanzado...");
    const page = await browser.newPage();
    console.log("2. Abierta una pestaña...");
    await page.goto(url);
    console.log(`3. Estamos en ${url}...`);
    
    await page.screenshot({path: `${fileName}.png`});
    console.log(`4. Guardada la imagen como ${fileName}.png...`);

    const result = await page.evaluate(() => {
        let data = []
        const issues = document.querySelectorAll("ul.js-navigation-container > li")
        issues.forEach(issue => {
            data.push({
            	"title": issue.querySelector("a.js-navigation-open").innerText,
            	"url": issue.querySelector("a.js-navigation-open").href,
            	"id": issue.id.replace("issue_", "")
            });
        });
        return data;
    });
    console.log(`5. Termiando el scrapeo...`);
    await browser.close();
    console.log(`6. Cerrando el Puppeteer...`)
    return result;
    
};


scrape().then((value) => {

    fs.writeFileSync(`${fileName}.json`, JSON.stringify(value, null, 4));
    console.log("7. Guardado JSON:", `${fileName}.json`);

    fs.writeFileSync(`${fileName}.md`, mdGenerator(value));
    console.log("8. Guardado MARKDOWN:", `${fileName}.md`);

    console.log("9. #luego");
});

function mdGenerator (data){
    let mdContent = "# Peliculas que ver...\n\n";
    data.forEach(film => {
        mdContent += `- [ ] ${film.title} [#${film.id}](${film.url})\n`;
    })
    return mdContent
}

```
- Genera `todo_peliculas.json`
```
[
    {
        "title": "Big Hero 6 ",
        "url": "https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/83",
        "id": "83"
    },
    {
        "title": "magia de la consola de Twitter ",
        "url": "https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/77",
        "id": "77"
    },
    {
        "title": "Video de algoritmo de ordenación Bubble danzando :) ",
        "url": "https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/59",
        "id": "59"
    },
    {
        "title": "¿Como es MVC? ",
        "url": "https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/57",
        "id": "57"
    },
    {
        "title": "Serie Silicon Valley ",
        "url": "https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/53",
        "id": "53"
    },
    {
        "title": "Viviendo de ser un \"security researcher\" ",
        "url": "https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/47",
        "id": "47"
    },
    {
        "title": "[Pelicula] Capital C ",
        "url": "https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/46",
        "id": "46"
    },
    {
        "title": "[Pelicula] Print the Legend ",
        "url": "https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/45",
        "id": "45"
    },
    {
        "title": "[MEME] This is fine ",
        "url": "https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/44",
        "id": "44"
    },
    {
        "title": "Humor diario ",
        "url": "https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/43",
        "id": "43"
    },
    {
        "title": "The Internet's Own Boy: The Story of Aaron Swartz ",
        "url": "https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/42",
        "id": "42"
    },
    {
        "title": "Gringo: The Dangerous Life of John McAfee ",
        "url": "https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/41",
        "id": "41"
    },
    {
        "title": "Pirate Radio. Film ",
        "url": "https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/40",
        "id": "40"
    },
    {
        "title": "Generador de portadas... ",
        "url": "https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/39",
        "id": "39"
    }
]
```
- Genera `todo_peliculas.md`
```
# Peliculas que ver...

- [ ] Big Hero 6  [#83](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/83)
- [ ] magia de la consola de Twitter  [#77](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/77)
- [ ] Video de algoritmo de ordenación Bubble danzando :)  [#59](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/59)
- [ ] ¿Como es MVC?  [#57](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/57)
- [ ] Serie Silicon Valley  [#53](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/53)
- [ ] Viviendo de ser un "security researcher"  [#47](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/47)
- [ ] [Pelicula] Capital C  [#46](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/46)
- [ ] [Pelicula] Print the Legend  [#45](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/45)
- [ ] [MEME] This is fine  [#44](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/44)
- [ ] Humor diario  [#43](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/43)
- [ ] The Internet's Own Boy: The Story of Aaron Swartz  [#42](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/42)
- [ ] Gringo: The Dangerous Life of John McAfee  [#41](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/41)
- [ ] Pirate Radio. Film  [#40](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/40)
- [ ] Generador de portadas...  [#39](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/issues/39)
```
- Genera `todo_peliculas.png`
![todo_peliculas](https://user-images.githubusercontent.com/5110813/39935222-98a0d5f0-5548-11e8-82c1-d5c9b332d925.png)
